### ISSUE TITLE
Error: Cannot find module 'ora'

### ISSUE THREAD

**Issue by cherishman2005** [bfenetworks/dashboard#13]
```
Error: Cannot find module 'ora'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/nginx/proxy/dashboard-develop/configs/build.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
build failed!
```

**Comment by linzc** [comment]
此问题一般是由于依赖没有安装好导致的，可重新安装后再试：
1.进入项目文件夹，（可先备份一下项目）删除node_modules文件和package-lock.json文件。注意不是package.json（如果删不掉，确认项目是不是打开了，关闭再试）
2.在项目下运行npm install
3.继续运行npm run dev(这里不一定是dev，需根据实际项目中的配置，启动项目)
如果提示需要安装其他插件，再继续安装插件，重启即可。
